; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Sat Jul 04 2020 19:19:39 GMT-0300 (Argentina Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


