; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Sat Jul 04 2020 19:19:39
M561 ; clear any bed transform

G28 ; home
M401 ; deploy Z probe (omit if using bltouch)
G30 P0 X30 Y160 Z-99999 ; probe near a leadscrew, half way along Y axis
G30 P1 X250 Y160 Z-99999 S2 ; probe near a leadscrew and calibrate 2 motors
M402 ; retract probe (omit if using bltouch)



