; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Sat Jul 04 2020 19:19:39 GMT-0300 (Argentina Standard Time)
M280 P0 S90 ; retract BLTouch

