; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Sat Jul 04 2020 19:19:39 GMT-0300 (Argentina Standard Time)

